- hosts: localhost
  become: true
  pre_tasks:
    - name: Update all Debian/Ubuntu packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
      tags:
        - install
        - dotfiles
        - productivity
        - zsh
        - stow
        - node
        - rust
        - java
        - maven
        - lazygit
        - nvim
  tasks:
    - name: Include Zsh
      include_tasks: tasks/zsh.yml

    #- name: Include Node
    #include_tasks: tasks/node.yml

    - name: Include Dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: Include Utils
      include_tasks: tasks/utils.yml

    #- name: Install rust
    #  include_tasks: tasks/rust.yml

    #- name: Install Java Amazone corretto
    #  include_tasks: tasks/java.yml

    #- name: Include LazyGit
    #  include_tasks: tasks/lazygit.yml

    #- name: Include Maven
    #include_tasks: tasks/maven.yml

    - name: Include nerdfont
      include_tasks: tasks/nerd-font.yml

    - name: Include nvim / lazyvim
      include_tasks: tasks/nvim.yml
