- name: Install need utils for nerd fonts
  become: true
  apt:
    name: ["unzip", "fontconfig"]
  tags:
    - install
    - productivity
    - nvim

- name: Ensure the local fonts directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: "0755"
  tags:
    - install
    - productivity
    - nvim

- name: Download JetBrainsMono Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMono.zip"
  tags:
    - install
    - productivity
    - nvim

- name: Unzip JetBrainsMono Nerd Font
  unarchive:
    src: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMono.zip"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: yes
  tags:
    - install
    - productivity
    - nvim

- name: Remove the JetBrainsMono zip file
  file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMono.zip"
    state: absent
  tags:
    - install
    - productivity
    - nvim

- name: Update font cache
  command: fc-cache -fv
  tags:
    - install
    - productivity
    - nvim
