- name: Update APT package list
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - install
    - productivity
- name: Install packages
  become: true
  apt:
    name:
      [
        "tmux",
        "curl",
        "git",
        "xclip",
        "ripgrep",
        "fd-find",
        "jq",
        "tldr",
        "wget",
        "protobuf-compiler",
        "tar",
      ]
  tags:
    - install
    - productivity

- name: Ensure necessary packages are installed
  apt:
    name:
      - curl
      - tar
    state: present
    update_cache: yes
  tags:
    - install
    - productivity

- name: Download and install Starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    executable: /bin/sh
  tags:
    - install
    - productivity
