- name: Install packages
  become: true
  apt:
    name: ["tmux", "curl", "git", "xclip", "tldr", "ripgrep"]
  tags:
    - install
    - productivity

- name: make sure curl is installed
  package:
    name: curl
    state: present
  tags:
    - install
    - productivity

- name: Download and install Starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    executable: /bin/sh
  tags:
    - install
    - productivity
